<a href="https://colab.research.google.com/github/calebroykim/gitstudy/blob/master/numpy(%EA%B9%80%EC%98%81%EC%A3%BC_2023152498).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
type(a)

numpy.ndarray

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5]])

In [7]:
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [8]:
a.shape

(6,)

In [9]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [10]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[0,1]

2

In [12]:
a[0]

array([1, 2, 3, 4])

In [15]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(2)

array([1., 1.])

In [19]:
np.empty(2)

array([1., 1.])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.arange(2, 8, 2)

array([2, 4, 6])

In [23]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [25]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [29]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [31]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [36]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
array_example = np.array([[[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]],])

In [42]:
array_example.ndim

4

In [43]:
array_example.size

24

In [44]:
array_example.shape

(1, 3, 2, 4)

In [45]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [52]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [53]:
np.reshape(a, newshape=(1,6), order='c')

array([[0, 1, 2, 3, 4, 5]])

In [54]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [56]:
row_vector

array([[0, 1, 2, 3, 4, 5]])

In [55]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [57]:
col_vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [58]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [59]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [60]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [61]:
data = np.array([1, 2, 3])

In [62]:
data[1]

2

In [63]:
data[0:2]

array([1, 2])

In [64]:
data[1:]

array([2, 3])

In [69]:
data[-2:]

array([2, 3])

In [79]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [80]:
print(a[a < 5])

[1 2 3 4]


In [81]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [82]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [83]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [84]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [87]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [88]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [89]:
print(a[b])

[1 2 3 4]


In [90]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [91]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [93]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [94]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [95]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [96]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [97]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [98]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [99]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [100]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [101]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [102]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [106]:
data - ones

array([0, 1])

In [107]:
data * data

array([1, 4])

In [108]:
data / data

array([1., 1.])

In [109]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [110]:
b = np.array([[1, 1], [2, 2]])

In [111]:
b.sum(axis=0)

array([3, 3])

In [112]:
b.sum(axis=1)

array([2, 4])

In [113]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [114]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [115]:
a.sum()

4.8595784

In [116]:
a.min()

0.05093587

In [118]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [119]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [120]:
data[0, 1]


2

In [121]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [122]:
data[0:2, 0]

array([1, 3])

In [123]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [124]:
data.max(axis=0)

array([5, 6])

In [125]:
data.max(axis=1)

array([2, 5, 6])

In [126]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [127]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [128]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [129]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [132]:
np.random.random((3, 2))

array([[0.62156268, 0.57910998],
       [0.67078625, 0.96419797],
       [0.78714597, 0.27056053]])

In [133]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [134]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [135]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [136]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [138]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [139]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [140]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [142]:
print(indices)

[0 1 2]


In [143]:
print(occurrence_count)

[2 1 1]


In [145]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [146]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [147]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [148]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [149]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [150]:
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [151]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [152]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [153]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [154]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [155]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [156]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [157]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [158]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [159]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
